from .index.views import IndexView
from .profile.views import ProfileView
from .upload_photo.views import UploadPhoto
from .edit_photo.views import EditPhoto
from .view_versions.views import ViewPhotoVersions
from .delete_photo.views import DeletePhoto
from .recover_photo.views import RecoverPhoto
from .search.views import SearchView
from .sort.views import SortView
from .create_like.views import CreateLike
from .remove_like.views import RemoveLike