# Generated by Django 5.1 on 2024-10-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('TBD', 'To Be Deleted'), ('APR', 'Approved'), ('DEN', 'Denied'), ('OM', 'On Moderation')], default='OM', max_length=16),
        ),
    ]
