# Generated by Django 5.1 on 2024-11-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_alter_comment_parent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('photo', 'user'), name='unique_photo_user'),
        ),
    ]
