# Generated by Django 5.1.4 on 2025-02-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_like_unique_photo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='photoversion',
            options={'verbose_name': 'photo_version', 'verbose_name_plural': 'photo_versions'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='photos',
        ),
        migrations.AlterModelTable(
            name='photoversion',
            table='photo_versions',
        ),
    ]
