# Generated by Django 5.1.4 on 2025-02-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_alter_comment_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user_profile', 'verbose_name_plural': 'user_profiles'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
