# Generated by Django 5.1.4 on 2025-02-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_alter_userprofile_options_alter_userprofile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoversion',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='photoversion',
            name='status',
        ),
        migrations.AddField(
            model_name='photoversion',
            name='iteration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
