# Generated by Django 5.1.4 on 2025-02-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_remove_photoversion_pub_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='photoversion',
            constraint=models.UniqueConstraint(fields=('photo', 'iteration'), name='unique_photo_iter'),
        ),
    ]
