# Generated by Django 5.1.4 on 2025-03-11 10:42

from django.db import migrations, models

ROLE_USER = "USR"
ROLE_MOD = "MOD"
ROLE_ADMIN = "ADM"

def set_role(apps, schema_editor):
    UserProfile = apps.get_model("models_app", "UserProfile")
    for user in UserProfile.objects.all():
        if user.is_superuser and user.is_staff:
            user.role=ROLE_ADMIN
        elif user.is_staff:
            user.role=ROLE_MOD
        else:
            user.role=ROLE_USER
        user.save(update_fields=["role"])

class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0008_photoversion_unique_photo_iter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USR', 'User'), ('MOD', 'Moderator'), ('ADM', 'Administrator')], default='USR'),
        ),
        migrations.RunPython(set_role)
    ]
