# Generated by Django 5.1.4 on 2025-03-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('models_app', '0010_reviewticket'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewticket',
            constraint=models.UniqueConstraint(fields=('object_id', 'content_type'), name='unique_review_photo'),
        ),
    ]
