# Generated by Django 5.1.4 on 2025-06-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0012_alter_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewticket',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
