# Generated by Django 5.1.4 on 2025-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('models_app', '0013_reviewticket_is_seen'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email_for_user'),
        ),
    ]
